apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blacksentinel-vault-ingress
  namespace: blacksentinel-vault
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vault.blacksentinel.com
      secretName: blacksentinel-vault-tls
  rules:
    - host: vault.blacksentinel.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blacksentinel-web-console
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: blacksentinel-api-gateway
                port:
                  number: 80
