apiVersion: v1
kind: Secret
metadata:
  name: blacksentinel-vault-secrets
  namespace: blacksentinel-vault
type: Opaque
data:
  DATABASE_URL: ZGF0YWJhc2VfdXJsX2VuY29kZWQ=
  REDIS_URL: cmVkaXNfdXJsX2VuY29kZWQ=
  JWT_SECRET:_andvbXNfawVjX2VuY29kZWQ=
  MASTER_KEY: bWFzdGVyX2tleV9lbmNvZGVk
  WRAPPING_KEY: d3JhcHBpbmdfa2V5X2VuY29kZWQ=
